root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "go build -o /tmp/air/server ."
  bin = "/tmp/air/server"
  include_ext = ["go"]
  exclude_dir = ["static", ".git"]
  delay = 500

[screen]
  clear_on_rebuild = true
